#CaveWars 1.0.4 - Paper 1.21.10 / Java 21
#Tue Sep 22 15:53:18 CEST 2026
arena-height=18
arena-radius=20
auto-start-seconds=30
border-damage=2
border-enabled=true
border-final-size=6
border-shrink-seconds=180
border-start-seconds=600
game-duration-seconds=900
grace-seconds=90
max-players=4
min-players=2
pvp-after-seconds=120
reset-after-game=true
starter-bread=4
starter-torches=8
